### ISSUE TITLE
Design the coding style

### ISSUE THREAD

**Issue by cmj0121** [pysisyphus/Sisyphus#2]
Please survey and design the coding style for this project.
For example, you can survey the [pylint](https://www.pylint.org/) and add as the default check when push code.

**Comment by sfffaaa** [comment]
If we decide use flake8, please follow below instructions for local hook.
1. pip3 install flake8
2. flake8 --install-hook git
3. git config --bool flake8.strict true

**Comment by cmj0121** [comment]
Change from flake8 to pylint (default python3 package)
@sfffaaa please review the .pylintrc file and add/delete PEP8 rules if need

**Comment by sfffaaa** [comment]
@cmj0121 pylint is also good for me.
Besides, I found there is a [.pylintrc](https://gist.github.com/rpunkfu/3cd6f8b8b23e27adedbd) example which based on Google Style Guide for Python.
I think we can use it as our pylint rules.

Of course, we need to disable line-too-long rule, it's annoying.

**Comment by cmj0121** [comment]
RECOMMEND: using the customized .pylintrc is more flexible for our project

**Comment by sfffaaa** [comment]
Take it. If we don't follow other's coding style, I think our pylintrc is ok right now. If we encounter other warnings, we can update rules.
