### ISSUE TITLE
Add requirements for submodule

### ISSUE THREAD

**Issue by sfffaaa** [pysisyphus/Sisyphus#3]
Module, setproctitle, is needed, otherwise, process cannot execute.

**Comment by cmj0121** [comment]
Using the pipenv as the following command

```
> pipenv install
> pipenv shell
```

**Comment by sfffaaa** [comment]
@cmj0121  Thanks! pipenv works and install_requires entry inside setup.py includes 'setproctitle'. So it doesn't need to add requirements file. Let me close it.
